#####################################
### FOR DEVELOPMENT PURPOSES ONLY ###
#####################################

version: '3'

services:
  ######## VUE  ########
  vue:    
    image: tjdft/vue-ssr:latest
    user: root
    restart: always
    entrypoint: /bin/bash -c "echo 'Done! keep container running :)' && tail -F /dev/null"
    environment: 
        - HOST=0.0.0.0        
    volumes:
      - ../:/var/www/web:cached          
    ports:
     - 3000:3000     